# Generated by Django 5.0.1 on 2024-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='download',
            field=models.CharField(max_length=50),
        ),
    ]
