# Generated by Django 5.0.1 on 2024-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_projects_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='title',
        ),
        migrations.AddField(
            model_name='education',
            name='ended_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exprience',
            name='ended_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exprience',
            name='started_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
