# Generated by Django 5.0.1 on 2024-01-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_education_ended_at_alter_education_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exprience',
            name='ended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exprience',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
