# Generated by Django 5.0.1 on 2024-01-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_skills_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='picture',
            field=models.ImageField(default=1, upload_to='cv_picture'),
            preserve_default=False,
        ),
    ]
