# Generated by Django 5.0.1 on 2024-01-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_exprience_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='bio_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
