# Generated by Django 4.2.7 on 2024-02-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_contactmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='cvfile',
            field=models.FileField(default=1, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
